### ISSUE TITLE
File missing error

### ISSUE THREAD

**Issue by asalcedo31** [ChandraPedamallu/PathSeq#2]
Hello,

When I get to the annotate_hittable step I get the following errors:

/oicr/local/lib/jvm/jdk1.7.0_55/bin/java -Xmx4g -classpath /u/asalcedo/PathSeq//Java annotate_hittable /u/asalcedo/PathSeq//Java/names.dmp /u/asalcedo/PathSeq//Java/nodes.dmp /u/asalcedo/isilon/private/users/asalcedo/Pathseq_out/2_PathSeq/8403.qf_1.unique.fq1.unmappedfinal.fq1_1_spt/split.fq1.mega.hittable.2_4 /u/asalcedo/isilon/private/users/asalcedo/Pathseq_out/2_PathSeq/8403.qf_1.unique.fq1.unmappedfinal.fq1_1_spt/split.fq1.mega.annotate.hittable.2_4
(0, 'Error: /u/asalcedo/PathSeq/Java/nodes.dmp (No such file or directory)\njava.io.FileNotFoundException: /u/asalcedo/PathSeq/Java/nodes.dmp (No such file or directory)\n\tat java.io.FileInputStream.open(Native Method)\n\tat java.io.FileInputStream.<init>(FileInputStream.java:146)\n\tat java.io.FileInputStream.<init>(FileInputStream.java:101)\n\tat java.io.FileReader.<init>(FileReader.java:58)\n\tat annotate_hittable.main(annotate_hittable.java:91)')

/u/asalcedo/PathSeq/ is my local installation and nodes.dmp and names.dmp are missing from the Java folder. 

Thank you,

Adriana Salcedo

**Comment by ChandraPedamallu** [comment]
Hi Adriana,

Sorry for late response.

Please download the names.dmp, nodes.dmp from the NCBI taxonomy ftp.

Thank you.

Best
Chandra
