### ISSUE TITLE
workflow manager and documentation

### ISSUE THREAD

**Issue by wresch** [ChandraPedamallu/PathSeq#3]
Hi,

thank you for making PathSeq available on GitHub. Two questions though:  (1) are you planning to port this to a workflow manager? It's rather difficult to deal with large monolithic csh and python scripts (2) will there be more documentation? i have a rough idea of what the config file looks like from a previous issue but everything else is pretty much a black box and there are no useful error messages.

Regards,
Wolfgang

**Comment by mforde84** [comment]
yea, ditto. there's zero documentation for this.
  
  https://i.imgur.com/D5hUxPj.jpg

**Comment by ChandraPedamallu** [comment]
Hi Martin

I don’t understand what is this email about

Best

**Comment by mforde84** [comment]
Is there any documentation for deployment of the PathSeq pipeline? I understand that this git hasn't been actively updated in some time, but I have a end user asking if we could implement this software on our own systems. Unfortunately there's no documentation except for thousands of lines of python and awk code.

**Comment by ChandraPedamallu** [comment]
I have uploaded the documentation as README.pdf
