### ISSUE TITLE
Getting rid of TRF

### ISSUE THREAD

**Issue by roelj** [ChandraPedamallu/PathSeq#4]
Hello,

RepeatMasker seems to depend on the availability of TRF, which has the following license statement:

>  The author of this software grants to any individual or organization the right to use and to make an unlimited number of copies of this software. You may not de-compile, disassemble, reverse engineer, or modify the software. This software cannot be sold, incorporated into commercial software or redistributed. The author of this software accepts no responsibility for damages resulting from the use of this software and makes no warranty or representation, either express or implied, including but not limited to, any implied warranty of merchantability or fitness for a particular purpose. This software is provided as is, and the user assumes all risks when using it. 

So, automating the installation process is impossible, because we cannot (re)distribute TRF.
Can we get rid of this dependency in your pipeline?

**Comment by ChandraPedamallu** [comment]
Hi , sorry for late reply. Yes. We can skip the repeatmasker step in the config file.  Please let me know if this not clear.

**Comment by ChandraPedamallu** [comment]
Uploaded the README file
