### ISSUE TITLE
Cloning AMI

### ISSUE THREAD

**Issue by mhbakalar** [ChandraPedamallu/PathSeq#5]
Hello,
I am trying to clone the AMI to get started with pathseq. While running 'Build_OwnAMI', I am receiving the following error:

Client.InvalidAMIID.NotFound: The image id '[ami-00012347]' does not exist

Where do I get access to the AMI image? Thank you for the help, I am somewhat new to AWS.

**Comment by ChandraPedamallu** [comment]
Sorry this has been deprecated not supported any more.
